export const CHALLENGES: string[] = [
  // --- Innovation (50) ---
  "You've invented a device that translates your pet's thoughts into Shakespearean English. What's your marketing slogan?",
  "Design a new Olympic sport that involves zero physical activity.",
  "Create a social media platform for time travelers. What are its unique features and privacy concerns?",
  "Pitch a brand of paint that changes color based on the mood of the room's occupants.",
  "Your startup creates personalized weather forecasts that only predict hyper-specific, trivial events, like 'a 70% chance of your keys falling under the car seat.' How do you monetize it?",
  "Invent a food that makes you temporarily brilliant at one random, useless skill.",
  "Design a system for delivering packages via trained pigeons in an urban environment. What could go wrong?",
  "Propose a new holiday that everyone on Earth would celebrate. What is it for, and what are the traditions?",
  "Your company sells dreams as a subscription service. What are the different pricing tiers?",
  "Develop a technology that lets you 'un-ring' a bell. What are its most profound applications?",
  "Design a video game where the main objective is to be as boring as possible. What is the final boss?",
  "Create a cooking show where all the ingredients are inedible.",
  "Invent a new form of currency based on compliments. How is it regulated?",
  "Pitch a machine that materializes the perfect witty comeback, but only 24 hours after you needed it.",
  "Design a chair that actively tries to prevent you from sitting on it.",
  "What would be the user manual for the human brain? Write the first three instructions.",
  "Invent an app that pairs you with your 'nemesis'—the person on Earth most perfectly opposite to you. What's the goal?",
  "Design a theme park where the attractions are famous historical blunders.",
  "Create a language that can only be spoken while underwater.",
  "Pitch a set of tools designed for ghosts to interact with the physical world.",
  "Develop a perfume that smells like a specific memory (e.g., 'Grandma's kitchen,' 'first rock concert').",
  "Design a car horn that plays a sincere, polite apology instead of a loud honk.",
  "Invent a device that lets you experience the world from the perspective of an ant for 15 minutes.",
  "Create a new genre of music based on the sounds of a dial-up modem.",
  "Pitch a service that professionally and dramatically reads the Terms and Conditions for any product.",
  "Design a zoo for mythical creatures. What are the ethical considerations?",
  "Invent a type of bread that never goes stale but slowly gets more and more sarcastic.",
  "Create a search engine that only returns results from the year 1999.",
  "Design a robot whose only function is to make eye contact with you from across the room and nod reassuringly.",
  "Pitch a plant pot that moves around the house on its own to find the best sunlight.",
  "Invent a magical artifact that turns any book into a pop-up book. What classic novel do you try it on first?",
  "Design an alarm clock that wakes you up by gently telling you a comforting lie.",
  "Create a new chess piece. What is it, how does it move, and how does it break the game?",
  "Pitch a pair of glasses that lets you see the 'source code' of the universe.",
  "Invent a chewing gum that changes flavor to match the song you're listening to.",
  "Design a house where all the walls are trampolines.",
  "Create a service that provides alibis for socially awkward situations.",
  "Invent a type of ice cream that gets warmer as you eat it.",
  "Pitch a board game about the excitement of waiting in long lines.",
  "Design a musical where the cast is composed entirely of inanimate objects from a single kitchen drawer.",
  "Invent a device that captures the 'one that got away'—the perfect idea you had just before falling asleep.",
  "Create a clothing line that is invisible to security cameras.",
  "Design a vending machine that dispenses existential questions instead of snacks.",
  "Pitch a pen that refuses to write lies.",
  "Invent a sport played on the moon with lower gravity. What are the rules?",
  "Create an AI that generates conspiracy theories that are just plausible enough to be unsettling.",
  "Design a firework that's completely silent but creates beautiful, intricate shadows on the clouds.",
  "Invent a condiment that makes any food taste like it was cooked by a Michelin-star chef.",
  "Pitch a smartphone with no screen, only audio and haptic feedback.",
  "Create an escape room where the only way to get out is to make the room's AI moderator laugh.",
  // --- Business (50) ---
  "Your startup must monetize the feeling of déjà vu. What's the pitch?",
  "Design a subscription box service for ghosts. What are the first three items?",
  "You have to sell air conditioning to penguins in Antarctica. What's your slogan?",
  "Create a new social media platform exclusively for house plants. What is its killer feature?",
  "Your company's flagship product is a pill that makes you forget movie spoilers. How do you market it?",
  "Pitch a reality TV show where squirrels compete in an obstacle course for a golden acorn.",
  "Your startup provides emotional support animals, but they are all rocks. What is your value proposition?",
  "Monetize boredom. What is the service you provide?",
  "Design a brand of coffee that makes you more pessimistic. What's it called and why would anyone buy it?",
  "You are hired to rebrand the moon. What's your new marketing campaign?",
  "Create a business that only operates on February 29th. What does it do?",
  "Pitch a luxury hotel for insects. What are the amenities?",
  "You must sell a product that has literally no features. It's just a smooth, inert cube. What's the ad copy?",
  "Develop a business model for a private investigation agency run by cats.",
  "Create a 'negative' crowdfunding platform where people pay to prevent something from being created.",
  "Market a brand of water that has already been used to boil hot dogs. What's its name and target audience?",
  "Design a timeshare opportunity for a single park bench.",
  "Pitch an airline where the journey is the destination—flights take off and land at the same airport after a scenic, themed experience.",
  "Create a consulting firm that specializes in helping supervillains with their public relations.",
  "Your company sells pre-haunted houses to people who find regular houses too boring.",
  "Design an insurance policy that covers alien abduction. What are the premiums and loopholes?",
  "You have to market gravity as a premium subscription service. What are the free vs. paid features?",
  "Pitch a start-up that rents out professional-looking people to stand behind you and nod during your video calls.",
  "Create a fast-food chain that only serves the crusts of bread. What's it called?",
  "Develop a corporate wellness program based on competitive screaming.",
  "Your business is a 'reverse zoo' where animals come to watch humans in their natural habitat (an office).",
  "Design a celebrity-endorsed line of designer hard hats. Who is your first celebrity?",
  "Pitch a tech support service staffed entirely by people who have never used a computer.",
  "Create a high-end, artisanal brand of salt that is just regular table salt in a fancy jar. How do you justify the price?",
  "You are launching a new cryptocurrency called 'UselessCoin'. What is your whitepaper's abstract?",
  "Design a pop-up store that sells only the items you see in your dreams.",
  "Pitch a 'demotivational' speaker who charges companies to lower employee morale. Why would a company hire them?",
  "Market a smartphone with a battery life of exactly 10 minutes. What's the selling point?",
  "Create a restaurant where all the chefs are toddlers. What is on the menu?",
  "Your company is a 'break-up-for-hire' service that uses singing telegrams.",
  "Design a line of clothing for statues.",
  "Pitch a new streaming service that only shows paint drying, in 4K.",
  "Develop a business that replaces all the audio in famous movies with awkward lip-syncing by one person.",
  "You must launch a political campaign for a candidate who is a literal golden retriever. What are the campaign promises?",
  "Design a travel agency that specializes in disastrous vacations for adrenaline junkies.",
  "Pitch a business that sells bottled air from different historical periods.",
  "Create a law firm that exclusively represents fictional characters in their disputes with their authors.",
  "Market a self-help book titled 'Embrace Your Flaws: A Guide to Giving Up.'",
  "Design a gym where all the equipment is designed to be slightly inconvenient to use.",
  "Pitch a talent agency for people who are exceptionally good at being mediocre.",
  "Create a company that manufactures and sells convincing-looking fake trophies for any occasion.",
  "Your startup is a 'reverse-Tinder' where the algorithm finds the person you're least compatible with.",
  "Design a car that is powered by human disappointment. How does it work?",
  "Market a series of instructional videos on how to fail at everything gracefully.",
  "Pitch a gourmet restaurant that serves only different flavors of water.",
  // --- Knowledge & Smartness (50) ---
  "If the color blue tasted like something, what would it taste like and why?",
  "Explain a black hole to a golden retriever.",
  "What would be the most chaotic superpower to give to a house cat?",
  "You must describe the concept of 'irony' using only three physical objects. What are they?",
  "If you could add one new rule to the laws of physics, what would it be?",
  "What would be the most surprising item to find at the bottom of the Mariana Trench?",
  "If you had to write a Yelp review for the planet Earth, what would it say?",
  "How would you prove to a medieval king that you are from the future without using any technology?",
  "What is the sound of silence, and what color is it?",
  "You can have dinner with any three people, living or dead, but they all think you are their waiter. Who do you invite?",
  "If trees could scream, would we still cut them down? Why or why not?",
  "What piece of modern technology would be the most difficult to explain to Leonardo da Vinci?",
  "If you had to choose a theme song for humanity, what would it be?",
  "How would civilization be different if humans had to hibernate for three months every winter?",
  "You discover a new, primary emotion. What is it, and what does it feel like?",
  "What would be the title of the autobiography of the first self-aware AI?",
  "If you could ask the ocean one question, what would it be?",
  "What would be the national anthem of the Internet?",
  "If you had to hide a giraffe in a modern city, what is your plan?",
  "Explain the concept of infinity to a five-year-old.",
];

export const FUSION_BASE_CONCEPTS: string[] = [
  "a subscription box service for ghosts",
  "a brand of coffee that makes you more pessimistic",
  "a private investigation agency run by cats",
  "an airline where the journey is the destination",
  "a social media platform exclusively for house plants",
  "a 'demotivational' speaker who charges companies to lower employee morale",
  "a fast-food chain that only serves the crusts of bread",
  "a travel agency that specializes in disastrous vacations",
  "an insurance policy that covers alien abduction",
  "a high-end, artisanal brand of salt that is just regular table salt",
  "a consulting firm for supervillains",
  "a zoo for mythical creatures",
  "a timeshare opportunity for a single park bench"
];

export const FUSION_CHALLENGE_TEMPLATES: string[] = [
  "Your challenge is to build a business plan for: **{{IDEA}}**. First, every great (or terrible) idea needs a name. What is the name for this new company?",
  "Great name! Now, for '{{NAME}}', what's its marketing slogan? The one you'd put on a billboard.",
  "Let's get to the core of '{{NAME}}'. Describe its main feature or purpose in one or two sentences.",
  "Who is the primary target audience for '{{NAME}}'?",
  "What makes '{{NAME}}' unique? What's its secret sauce or competitive advantage?",
  "How will '{{NAME}}' make money? Describe its basic business model (e.g., subscription, one-time purchase, ads).",
  "What's the 'wild card' feature for '{{NAME}}'? An unexpected, fun, or bizarre element that makes it memorable.",
  "Describe the ideal first-time user experience for '{{NAME}}' in three simple steps.",
  "What's the biggest, most hilarious potential risk or downside to launching '{{NAME}}'?",
  "Finally, write a single, powerful sentence to pitch '{{NAME}}' to an investor.",
];

export const TOTAL_ROUNDS = 10;
export const ROUND_DURATION_SECONDS = 60;
